### PR TITLE
Removed Unused Code

### PR DESCRIPTION
**Pull request by TheBrokenRail**
This removed unused code, remove old XCode stuff, and add CMake files for the examples (that are not used by default).

Requires darlinghq/darling#778

### CODE REVIEW

**Comment by bugaevc** [comment]
Pretty sure we need *at least* `NSPlatform` (with subclasses). Please verify Foundation builds :slightly_smiling_face:

**Comment by TheBrokenRail** [comment]
I made a PR to turn the symlinks into regular files in Foundation, darlinghq/darling-foundation#8

I am going to try to build it now.

**Comment by TheBrokenRail** [comment]
It builds!

**Comment by TheBrokenRail** [comment]
Any Updates?

**Comment by TheBrokenRail** [comment]
Rebased!

**Comment by TheBrokenRail** [comment]
Any updates? I did confirm earlier that it does build.

**Comment by TheBrokenRail** [comment]
Rebased! Any updates?

**Comment by ahyattdev** [comment]
This is looking OK to me

**Comment by bugaevc** [comment]
I guess if we ever need to use any of those files, we can just bring them back?

**Comment by TheBrokenRail** [comment]
> I guess if we ever need to use any of those files, we can just bring them back?

Yeah, if we ever need these files, just use Git.

**Comment by TheBrokenRail** [comment]
I re-based my PR and it builds now.

Instructions:
```
git clone https://github.com/TheBrokenRail/darling.git -b patch-32
cd darling
git remote set-url origin https://github.com/darlinghq/darling.git # Fix Broken Submodules
git submodule update --init --recursive
rm -rf src/external/cocotron/
git clone https://github.com/TheBrokenRail/darling-cocotron.git -b remove-unused-code src/external/cocotron
rm -rf src/external/foundation/
git clone https://github.com/TheBrokenRail/darling-foundation.git -b move-cocotron src/external/foundation
```

**Review by facekapow — APPROVED** [review]
LGTM; tested and working.

**Comment by facekapow** [comment]
I'm going to merge this in because, as Sergey noted above, we can just bring back the files if we ever need them.

**Pull request merged**
