### PR TITLE
Add symbol for NSApplicationLaunchUserNotificationKey

### PR DESCRIPTION
**Pull request by sirnacnud**
Adds NSApplicationLaunchUserNotificationKey fixing https://github.com/darlinghq/darling/issues/1196

### CODE REVIEW

**Comment by CuriousTommy** [comment]
Thank you for your contribution!

**Comment by tien238lnd** [comment]
@sirnacnud I am a newbie on these stuff. I install Darling and then install an application (file .dmg), and meet the error like in the issue [1196](https://github.com/darlinghq/darling/issues/1196). Can you bring this PR to the darling source code? Or can you give me any instruction/ workaround so that I can fix the error? Thanks so much.

**Comment by sirnacnud** [comment]
The cocotron submodule in the main repo hasn't been updated to pull this fix in.

You can do it locally and then you will have the fix in your build. In your darling source clone do:
```
cd src/external/cocotron
git pull origin master
```

**Comment by tien238lnd** [comment]
@sirnacnud Thank for your instruction. I built again with your PR and passed your error. But now I meet another error:
```
Darling [~]$ /Applications/Zalo.app/Contents/MacOS/Zalo 
dyld: Symbol not found: _AVMediaTypeMuxed
  Referenced from: /Applications/Zalo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
  Expected in: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 in /Applications/Zalo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
abort_with_payload: reason: Symbol not found: _AVMediaTypeMuxed
  Referenced from: /Applications/Zalo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
  Expected in: /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
 in /Applications/Zalo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework; code: 4
Abort trap: 6 (core dumped)
```
Do you think this error can be fixed easily?

**Pull request merged**
